name: psci
channels:
- defaults
- conda-forge
dependencies:
- python=3.6
- matplotlib
- numpy
- pandas>=0.22.0
- jupyter
- seaborn
- nb_conda_kernels
- geopandas
- fiona
- shapely
- xlrd
- feather-format
- joblib
- scikit-learn
- openpyxl
- jupyterlab
- notebook

pip:
    - yapf
    - watermark
